name: Build Tagged Dev Container and Push Image

# This workflow looks for tags of the form:
#     '<IMAGE_NAME>--<IMAGE_TAG>'
# Example git tag: 'foobar-container--noble-1.23.42'
# This then parases to building src/foobar-container and docker tags it
# with 'noble-1.23.42' before pushing it to ghcr.
# <anything>--<anything> should work as long as there are two dashes.
# This way the whole repo of containers doesn't need to be built, and
# confusion about which container the tags are for should be avoided.

on:
  push:
    tags:
      - "*--*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: from-git-tag-see-info-above
  IMAGE_TAG: from-git-tag-also-see-code-below

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:

    - name: Extract dev container IMAGE_NAME (build target) from ref_name (git tag)
      id: extract_image_name
      env:
        TAGSTR: ${{ github.ref_name }}
      run: echo "IMAGE_NAME=${TAGSTR%%--*}" >> $GITHUB_ENV

    - name: Extract dev container IMAGE_TAG (container version) from ref_name (git tag)
      id: extract_image_tag
      env:
        TAGSTR: ${{ github.ref_name }}
      run: echo "IMAGE_TAG=${TAGSTR#*--}" >> $GITHUB_ENV

    - name: Checkout Repository
      id: checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      id: login_ghcr
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pre-build dev container image
      id: build-push
      uses: devcontainers/ci@v0.3
      with:
        eventFilterForPush: "push"
        subFolder: src/${{ env.IMAGE_NAME }}
        imageName: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        imageTag:  ${{ env.IMAGE_TAG }}
        push: always

    - name: Hash Retrieval Experiment
      id: hash
      run: docker images --digests --format "{{json .Digest}}"

    # This won't work until devcontainers/ci can provide a digest
    # - name: Generate artifact attestation
    #   id: attest
    #   uses: actions/attest-build-provenance@v2
    #   with:
    #     subject-name: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
    #     subject-digest: ${{ env.SHA }}
    #     push-to-registry: true